### ISSUE TITLE
[V11] Error message in console at NPC Sheet opening

### ISSUE THREAD

**Issue by Far2Casual** [Dorako/pf2e-dorako-ui#201]
```
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'renderNPCSheetPF2e'. Cannot read properties of undefined (reading 'length')
[Detected 2 packages: pf2e-dorako-ui, system:pf2e]
    at Object.fn (base-theme-hooks.js:174:53)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at NPCSheetPF2e._render (foundry.js:5813:13)
    at async NPCSheetPF2e._render (foundry.js:6488:5)
    at async maintainTagifyFocusInRender (pf2e.mjs:6:244663)
    at async NPCSheetPF2e._render (pf2e.mjs:16:105038)
    at async NPCSheetPF2e._render (pf2e.mjs:17:105051)
```
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:734
callAll @ foundry.js:687
_render @ foundry.js:5813
await in _render (async)
_render @ foundry.js:6488
(anonymous) @ pf2e.mjs:16
maintainTagifyFocusInRender @ pf2e.mjs:6
_render @ pf2e.mjs:16
_render @ pf2e.mjs:17
render @ foundry.js:5727
render @ foundry.js:7067
_onClickEntryName @ foundry.js:69585
🎁call_wrapped @ libWrapper-wrapper.js:507
checkClickDocumentName @ monks-active-tiles.js:2178
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁DocumentDirectory.prototype._onClickEntryName#0 @ libWrapper-wrapper.js:189
🎁call_wrapped @ libWrapper-wrapper.js:507
clickDocumentName @ monks-active-tiles.js:2171
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁ActorDirectory.prototype._onClickEntryName#0 @ libWrapper-wrapper.js:189
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by ExileofBrokenSky** [comment]
Same, Foundry V11, latest Dorako UI, FTC said Dorako UI.
Does it actually affect anything? dunno, but console reds makes my dopamine lower.

**Comment by Dorako** [comment]
Seems that something has happened with toggles recently. I've added a null check for this in the next release
