### ISSUE TITLE
Error thrown in hooked function '' for hook 'getItemSheetPF2eHeaderButtons'. i18n is not defined

### ISSUE THREAD

**Issue by robinsving** [Dorako/pf2e-dorako-ui#263]
Getting the following error whenever I try to edit any item:
`Foundry.js:753 ReferenceError: Error thrown in hooked function '' for hook 'getItemSheetPF2eHeaderButtons'. i18n is not defined
    at Object.fn (customization.js:137:12)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at _AncestrySheetPF2e._getHeaderButtons (foundry.js:5979:13)
    at _AncestrySheetPF2e._getHeaderButtons (foundry.js:7131:25)
    at _AncestrySheetPF2e._getHeaderButtons (pf2e.mjs:259:191390)
    at _AncestrySheetPF2e._renderOuter (foundry.js:5871:27)
    at _AncestrySheetPF2e._renderOuter (foundry.js:7060:30)
    at _AncestrySheetPF2e._render (foundry.js:5771:27)
    at async _AncestrySheetPF2e._render (foundry.js:6474:5)
`
Have turned off all other modules, and Dorako UI is the only culprit. Issue #201 looks similar to this, but a different Hook.

**Comment by Dorako** [comment]
This is logspam from the unmaintained misc send-to-chat settings. You can disable it to get rid of it.
![CleanShot 2023-10-26 at 21 53 14@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/0a13961c-a800-488e-baf2-df94e779e6fe)
I've adjusted the code for next release so it doesn't logspam, but since the feature doesn't work right I'm inclined to pull it.
