### ISSUE TITLE
Token Action HUD compatibility broken

### ISSUE THREAD

**Issue by laurieathey** [Dorako/pf2e-dorako-ui#347]
Token Action HUD recently had a 2.0 release. The HUD now won't render and I see the following error repeatedly:

```js
foundry.js:655  Error: Error thrown in hooked function '' for hook 'renderTokenActionHud'. Cannot read properties of undefined (reading 'dataset')
[Detected 1 package: pf2e-dorako-ui(3.7.6)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at #doEvent (foundry-esm.js:44921:17)
    at #render (foundry-esm.js:44366:20)
    at async Semaphore._try (foundry-esm.js:6645:19)Caused by: TypeError: Cannot read properties of undefined (reading 'dataset')
[Detected 1 package: pf2e-dorako-ui(3.7.6)]
    at Object.fn (ui-theme.js:84:20)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at #doEvent (foundry-esm.js:44921:17)
    at #render (foundry-esm.js:44366:20)
    at async Semaphore._try (foundry-esm.js:6645:19)
```
![image](https://github.com/user-attachments/assets/7690f389-6b88-48b3-bb97-5d5911a15dd1)

Disabling Dorako UI ( :( ) makes the HUD work again. 
Not sure if the error stems from Dorako or TAHUD but I'm reporting on both since it's the stack trace seems to indicate TAHUD but the error literally specifies dorako :/

**Comment by laurieathey** [comment]
Re-enabled Dorako (my UI looks terrible without it :( ) and now the token action HUD is rendering, and working but I still have the same error. 
Hadn't changed any settings at that point, maybe re-enabling triggers some process?

**Comment by Dorako** [comment]
That error basically means that the hook triggered, but when it reached the point where it tried to add the data theme attribute to the application, there was no element to add it to.
This should never actually stop TAH from rendering, it just didn't get to add Dorako UI styling on top.

It's possible that TAH has significantly changed its guts such that I can no longer assume that when the hook fires there's an element to style. Has TAH changed to app v2?

**Comment by laurieathey** [comment]
Aye, I think it was V2.0.6 IIRC.

**Comment by laurieathey** [comment]
Had a session:
None of my players had the TAH visible. After the sesh I asked a player to help test this.
- he had a different error to the one I showed you, something to do with deconstructing an object. Didn't think to ask for a copy paste, sorry. 
- He then updated the Interface Theme from No Theme to Foundry 2 and the error changed to the one I showed you, but TAH now renders. 
- Changing the interface theme to No Theme makes the error go away entirely.

That's all we could work out, hope it helps.
