### ISSUE TITLE
1.70 cannot be installed

### ISSUE THREAD

**Issue by apoapostolov** [Dorako/pf2e-dorako-ui#82]
setup.js:292 Error: An unexpected error occurred when downloading file https://github.com/Dorako/pf2e-dorako-ui/archive/refs/tags/v1.7.0.zip: Not Found
    at fetchWithTimeout (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/http.mjs:42:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/downloader.mjs:1:616

**Comment by Dorako** [comment]
fix'd
